netcf: upgrade to latest 0.2.8
Fix compile failure while gnulib upgraded to 2017-08-20.18
...
| In file included from ../../../git/gnulib/lib/printf-args.h:41:0,
|                  from ../../../git/gnulib/lib/printf-parse.h:29,
|                  from ../../../git/gnulib/lib/printf-parse.c:36:
| ./wchar.h:571:6: error: #if with no expression
|  # if
...

Update HOMEPAGE, SRC_URI since the formers are obsolete.

Update SRCREV, although version not change, but the former
was two years ago.

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>